version: "3.9"

services:
  react:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      WATCHPACK_POLLING: "true"

  backend:
    container_name: backend
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: ./backend
      dockerfile: Backend/Dockerfile
    ports:
      - 8080:80

  db:
    container_name: db
    image: mariadb
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
    volumes:
      - ./backend/integracja.sql:/docker-entrypoint-initdb.d/integracja.sql
    ports:
      - 3306:3306

  pma:
    container_name: pma
    image: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
    restart: always
    ports:
      - 8081:80
